### PR TITLE
Restructuring 3: The Special Edition

### PR DESCRIPTION
**Pull request by 122004**
It's not actually special. In fact, try to minimize its special-ness by making _*literally ever branch*_ use this framework. The structure is:

1) Make an interface in the subsystem/interfaces folder with the subsystem
2) Put functions that every real subsystem of this type should use (ex: every drivetrain should have methods to set wheel power, so put it in the interface). The interface has no code in it, but is essentially a template for actual code.
3) Make the actual subsystem class in subsystem/instances that:
> extends *SubsystemBase*
> implements *[the interface you created]*
and put actual code in for all the functions in your interface.

This is how code _needs_ to work. Not following these sorts of things is the reason merge conflicts happen.

@classygirl44 , a special Easter egg can be found within Robot Restructuring 2: Electric Boogaloo.

### CODE REVIEW

**Comment by 122004** [comment]
Awaiting testing for further review.

**Comment by 122004** [comment]
Please do not review *yet*

**Comment by 122004** [comment]
It works! It could work better, but for the sake of the restructuring, these commits are *tested working* for this push.

**Review by classygirl44 — APPROVED** [review]

**Review by Linkd-Aether — APPROVED** [review]
Looks very good, thank you for restructuring and making the drivetrain subsystem.

**Review by Silvery-Sheen — APPROVED** [review]

**Pull request merged**
