### PR TITLE
Subsystem Design

### PR DESCRIPTION
**Pull request by BenWertz**
These aren't complete yet, but every branch should have all the subsystem programs to avoid merge conflicts.

### CODE REVIEW

**Review by Silvery-Sheen — DISMISSED** [review]
Just added a skeleton for different mechanisms that's unharmful...

**Review by 122004 — APPROVED** [review]
Great start 👍

**Review by 122004 — CHANGES_REQUESTED** [review]
There was an issue with the way this was structured.

**Review by Linkd-Aether — APPROVED** [review]

**Review by Linkd-Aether — APPROVED** [review]
These skeletons should come in handy for starting branches and keeping organized, thank you.

**Review by Silvery-Sheen — APPROVED** [review]

**Review by 122004 — APPROVED** [review]

**Pull request merged**
